### ISSUE TITLE
I want to ask when the source code will be released. Thank you

### ISSUE THREAD

**Issue by ycyinchao** [thograce/BGNet#1]
I want to ask when the source code will be released. Thank you

**Comment by thograce** [comment]
Did you leave the wrong message? The source code has been uploaded for more than a month.

**Comment by thograce** [comment]
> I want to ask when the source code will be released. Thank you

Did you leave the wrong message? The source code has been uploaded for more than a month.

**Comment by thograce** [comment]
> I want to ask when the source code will be released. Thank you

There are about three networks with the same name. Please carefully compare the titles, author information and publishing platforms of these papers.
