### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by ruankang1** [thograce/BGNet#11]
When I test I get the following error:
None of the test results matched the original image
The result is not related to the original image
For example:
![image](https://user-images.githubusercontent.com/130673178/236791634-ba7f0cae-11ab-446c-9bad-b2499bfd694d.png)
![image](https://user-images.githubusercontent.com/130673178/236791834-2fb35251-a956-4f2e-9501-0d93f6de28e7.png)
What's the problem, please?

**Comment by thograce** [comment]
Please check if the model path in your etest.py is correct.
![1683548195068](https://user-images.githubusercontent.com/26481692/236821602-249678af-8ef6-48d9-9d1d-d8cb2acbec73.png)

**Comment by ruankang1** [comment]
I have checked and confirmed to comply with all the requirements, but the test results are still not good. Do you know why?
<img width="839" alt="image" src="https://user-images.githubusercontent.com/130673178/236982356-4a544064-b72d-4bef-8cee-e12f5db6d189.png">

**Comment by ruankang1** [comment]
I have solved the problem.All you need to do is set the root directory, which corresponds to each other.
![屏幕截图 2023-05-09 210855](https://github.com/thograce/BGNet/assets/130673178/45c5ce59-0990-4eb8-b20e-ec87da87d007)

**Comment by HHHHHuan** [comment]
My error is the same, but I didn't get the correct result when I added root.
