### ISSUE TITLE
about the evalution

### ISSUE THREAD

**Issue by Censhengcai** [thograce/BGNet#5]
we dowmnoaded the BGNet.pth ，then run the etest.py to generate the predicted results, finally I run the eval.py.  I get the final evalution metrics.   But I found that the metric results which I tested has a big gap with that in the paper. could you tell what  problems in me  my steps. It is very importance for me!  thanks your great  contrubitions!

**Comment by thograce** [comment]
> we dowmnoaded the BGNet.pth ，then run the etest.py to generate the predicted results, finally I run the eval.py. I get the final evalution metrics. But I found that the metric results which I tested has a big gap with that in the paper. could you tell what problems in me my steps. It is very importance for me! thanks your great contrubitions!

There is nothing wrong with your process. I downloaded the model and tested it, and the result was correct. I don't know why you get different results. You can send your WeChat to my mailbox: thograce@163.com and we can chat on WeChat.

**Comment by Censhengcai** [comment]
my Wechat is 18378913458, thanks you!





------------------&nbsp;Original message&nbsp;------------------
From: "thograce"; 
Sendtime: Monday, Sep 19, 2022 10:10 AM
To: "thograce/BGNet"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [thograce/BGNet] about the evalution (Issue #5)





  
we dowmnoaded the BGNet.pth ，then run the etest.py to generate the predicted results, finally I run the eval.py. I get the final evalution metrics. But I found that the metric results which I tested has a big gap with that in the paper. could you tell what problems in me my steps. It is very importance for me! thanks your great contrubitions!
  
There is nothing wrong with your process. I downloaded the model and tested it, and the result was correct. I don't know why you get different results. You can send your WeChat to my mailbox: ***@***.*** and we can chat on WeChat.
